### ISSUE TITLE
pls tutor

### ISSUE THREAD

**Issue by malikalfazri** [reuben-dutton/squabble-bot#1]
how to use bro?

**Comment by varunnguptaa** [comment]
how do you use it?

**Comment by reuben-dutton** [comment]
this was an exercise for myself, and was not intended to be a final polished product for widespread use. i've only put it on github for myself and for others who might be interested in the approach and concepts used

i will not be providing assistance on how to use it to bot the game for you (what's the point beyond it being an intellectual exercise?)
if you have questions about specific pieces of code or ideas within then i'll gladly welcome those instead
